### ISSUE TITLE
DUB appears broken in this Docker image

### ISSUE THREAD

**Issue by r4j4h** [lindt/docker-ldc#1]
Failed to invoke the compiler ldc2 to determine the build platform:

```
root@machine:/c/code/src# dub
Failed to invoke the compiler ldc2 to determine the build platform:
```

Note that dub is installed

```
root@machine:/c/code/src# which dub
/dlang/ldc-1.2.0-beta2/bin/dub
```

and seems to be able to run as long as compilation is not utilized:

```
root@machine:/c/code/src# dub run -h
USAGE: dub run [<package>] [<options...>] [-- <application arguments...>]
......snip....
root@machine:/c/code/src# dub init
Package recipe format (sdl/json) [json]:
```

# Expected results

The following is the same manual scenario but with the latest `dlanguage/dmd`:

```
root@machine:/c/code/src# dub

Neither a package description file, nor source/app.d was found in
... snip....
No valid root package found - aborting.
```
# Additional Notes

Installing `dub` via `apt-get` (base docker image used's package manager, which has dub entries) does not resolve the issue.

**Comment by lindt** [comment]
tried to solve it together with [@s-ludwig](https://github.com/s-ludwig). We both cannot find a clue why it does not work with that version.
Apparently it is now working with the latest version.
Would be nice if you could try the following:

`docker run -ti dlanguage/ldc:1.3.0-beta1 dub`

**Comment by r4j4h** [comment]
Yay!! `1.3.0-beta1` works well! :) Thank you both for looking into it and discovering it works with the latest version.
