### ISSUE TITLE
Install command will fail with updated install.sh script

### ISSUE THREAD

**Issue by jondegenhardt** [lindt/docker-ldc#3]
The command:

 `bash /tmp/install.sh -p /dlang install -s "${COMPILER}-${COMPILER_VERSION}"`

fails with recent changes to the install.sh script on the site. See https://github.com/dlang/installer/pull/258. The change is to validate arguments, and `-s` is not a recognized argument. This will affect the docker-dmd Dockerfile as well.

**Comment by MartinNowak** [comment]
Indeed `-s` was never a valid argument to the install script, it was a [bash(1)](https://linux.die.net/man/1/bash) argument for the `curl | bash -s dmd` variant to read the script from stdin.
We could change the error to just a warning if necessary.
