### ISSUE TITLE
Custom entrypoint breaks use with Gitlab CI

### ISSUE THREAD

**Issue by JohanEngelen** [lindt/docker-ldc#8]
The docker image cannot be used with Gitlab CI because of this bug: https://gitlab.com/gitlab-org/gitlab-runner/issues/1253

Is the custom entrypoint really necessary? (why does this D language package include gosu? :) )

**Comment by JohanEngelen** [comment]
Link to related Gitlab runner issue: https://gitlab.com/gitlab-org/gitlab-runner/issues/1757

**Comment by lindt** [comment]
works now for gdc, ldc and dmd thanks to your PR.
to demonstrate i just now set up a simple sample gitlab project.
https://gitlab.com/dlang/example-docker-ci
